services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongo-data:/data/db

  libretranslate:
    image: libretranslate/libretranslate
    container_name: libretranslate
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - libretranslate-data:/app/data
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
    environment:
      - LT_DEBUG=true
      - LT_UPDATE_MODELS=false
      - LT_LOAD_ONLY=en,pl

  piper:
    image: artibex/piper-http
    container_name: piper
    environment:
      - MODEL_DOWNLOAD_LINK=https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/lessac/high/en_US-lessac-high.onnx?download=true

  app:
    build: .
    container_name: express-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - libretranslate
      - piper
    environment:
      - MONGO_URI=mongodb://mongodb:27017/readerdb
      - JWT_SECRET=${JWT_SECRET}
      - TRANSLATE_API_URL="http://libretranslate:5000"
      - TTS_API_URL=http://piper:5000
    volumes:
      - ./src:/app/src
      - /app/node_modules
    command: npm run dev

volumes:
  mongo-data:
  libretranslate-data: